add-highlighter global/ number-lines -hlcursor
add-highlighter global/ wrap -word -width 80
add-highlighter global/ show-matching

set global tabstop 2
set global indentwidth 0

set-option global ui_options terminal_assistant=none

map global normal <esc> ";," -docstring 'clear highlighted text and remove multiple cursors'

map global normal D xd -docstring 'delete line'
map global normal '#' ':comment-line<ret>' -docstring 'comment line'

map global normal <tab> ':b ' -docstring 'switch buffer'
map global normal <c-w> ':delete-buffer<ret>' -docstring 'delete buffer'

# hook global NormalKey y %{ nop %sh{
#   printf %s "$kak_main_reg_dquote" | xsel --input --clipboard
# }}

map global user y '<a-|>xsel --input --clipboard<ret>:echo "yanked to clipboard"<ret>' -docstring 'yank to clipboard'
map global user p '<a-!>xsel --output --clipboard<ret>:echo "pasted from clipboard"<ret>' -docstring 'paste from clipboard'
map global user r '<a-|>sh<ret>:echo "run in shell"<ret>' -docstring 'run selection in shell'

hook global WinSetOption filetype=julia %{
    map window insert <a-a> α
    map window insert <a-b> β
    map window insert <a-c> γ
    map window insert <a-d> δ
    map window insert <a-e> ε
    map window insert <a-f> φ
    map window insert <a-g> γ
    map window insert <a-h> η
    map window insert <a-i> ι
    map window insert <a-k> κ
    map window insert <a-l> λ
    map window insert <a-m> μ
    map window insert <a-o> ω
    map window insert <a-p> π
    map window insert <a-r> ρ
    map window insert <a-s> σ
    map window insert <a-t> τ
    map window insert <a-x> ξ
    map window insert <a-z> ζ
    map window insert <a-=> ≈
    map window insert <a-s-l> ℓ
    map window insert <a-s-p> ∂
    map global user j ':repl-send-text<ret>'
    map global user J ':repl-new julia<ret>'
    map global user h '<a-!>tac ~/.julia/logs/repl_history.jl | sed "/^#/Q; s/^\t//" | tac<ret>' -docstring 'paste last element from julia history'
}

set-face global MatchingChar black,green+b
