add-highlighter global/ number-lines
add-highlighter global/ wrap -word -width 80
add-highlighter global/ show-matching

set global tabstop 2
set global indentwidth 2

map global normal D <a-x>d -docstring 'delete line'
map global user '#' ':comment-line<ret>' -docstring 'comment line'
map global normal <tab> ':bn<ret>' -docstring 'switch to the next buffer'
map global normal <c-w> ':delete-buffer<ret>' -docstring 'delete buffer'

hook global NormalKey y %{ nop %sh{
  printf %s "$kak_main_reg_dquote" | xsel --input --clipboard
}}
