add-highlighter global/ number-lines
add-highlighter global/ wrap -word -width 80
add-highlighter global/ show-matching

set global tabstop 2
set global indentwidth 0

map global normal D <a-x>d -docstring 'delete line'
map global normal '#' ':comment-line<ret>' -docstring 'comment line'

map global normal <tab> ':bn<ret>' -docstring 'switch to the next buffer'
map global normal <s-tab> ':bp<ret>' -docstring 'switch to the previous buffer'
map global normal <c-w> ':delete-buffer<ret>' -docstring 'delete buffer'

hook global NormalKey y %{ nop %sh{
  printf %s "$kak_main_reg_dquote" | xsel --input --clipboard
}}

hook global WinSetOption filetype=julia %{
    map window insert <a-a> α
    map window insert <a-b> β
    map window insert <a-c> γ
    map window insert <a-d> δ
    map window insert <a-e> ε
    map window insert <a-f> φ
    map window insert <a-g> γ
    map window insert <a-h> η
    map window insert <a-i> ι
    map window insert <a-k> κ
    map window insert <a-l> λ
    map window insert <a-m> μ
    map window insert <a-o> ω
    map window insert <a-p> π
    map window insert <a-r> ρ
    map window insert <a-s> σ
    map window insert <a-t> τ
    map window insert <a-x> ξ
    map window insert <a-z> ζ
    map window insert <a-=> ≈
}
