conky.config = {
background = true,
use_xft = true,
font = 'sans:size=9',
xftalpha = 1,
update_interval = 1.0,
total_run_times = 0,
own_window = true,
own_window_transparent = true,
own_window_type = 'override',
own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
double_buffer = true,
minimum_height = 225,
maximum_width = 240,
draw_shades = false,
draw_outline = false,
draw_borders = false,
draw_graph_borders = false,
default_color = 'white',
default_shade_color = '000000',
default_outline_color = 'd9d7d6',
alignment = 'top_right',
gap_x = 12,
gap_y = 12,
no_buffers = true,
uppercase = false,
cpu_avg_samples = 2,
override_utf8_locale = false,
}

conky.text = [[
${font sans:size=9}CPU${font} ${cpubar cpu0}
${font sans:size=9}RAM${font} ${membar}
${font sans:size=9}Disk${font} ${fs_bar}
Uptime: $alignr $uptime
]]
